services:
  python:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      - ./bancos:/code/bancos
    links:
      - redis
    environment:
      - PORT_REDIS=6379
      - HOST_REDIS=redis

  redis:
    image: redis
    volumes:
      - dados_redis:/data
      
volumes:
  dados_redis: